### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by marithpl** [jvitkauskas/homeassistant_salus#9]
I really appreciate your good job.
I've got a question if is possible to extract to HA two things:
1) Humidity form thermostats
2) Some thermostats eg. SQ610 have function "Comfort floor" available in installer menu.
Comfort mode is turn on heating for X minutes every hour to maintain comfortable warm floor.
I really excited of this feature but it's not economic for heating for ex. at night. I wish to have this attribute to make automation when comfort floor should be turned on or off.

**Comment by jvitkauskas** [comment]
1. Humidity for SQ610 was added by @albei I don't have that model, so I can't test. Are you talking about SQ610?
2. Do you have this function available in the official app?

**Comment by albei** [comment]
The function exists in the app as a settings that you can access in advance mode. Gonna try search for it in Salus ha

**Comment by marithpl** [comment]
I use SQ610RF, and I have humidity in in Salus App but not in HA.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/25366097/106381509-8a943380-63b9-11eb-8aad-f7f6b38d62d9.png">
<img width="471" alt="image" src="https://user-images.githubusercontent.com/25366097/106381531-bca59580-63b9-11eb-8eee-52f54af3efc1.png">

**Comment by albei** [comment]
You can look humidity up in developer tools in States section. Look it up by name. 

If you wanna us it you have to make a custom sensor in your configuration.yaml with the humidity parameter like this.
`   climate_YOUR_THERMO_NAME_humidity:
        friendly_name: "You can chose your friendly name"
        unit_of_measurement: '%'
        value_template: "{{state_attr ('thermostat_entity_name', 'current_humidity')}} "`

**Comment by marithpl** [comment]
I can't see humidity. Maybe I need to update a module?
<img width="427" alt="image" src="https://user-images.githubusercontent.com/25366097/106381889-2626a380-63bc-11eb-8435-c21e97c4511b.png">

**Comment by albei** [comment]
What version do you have installed?
Looks like you have previous version of pyit600 since you dont have the complete hvac_modes.
it should look like this
```yaml
hvac_modes:
  - 'off'
  - heat
  - auto
min_temp: 5
max_temp: 35
preset_modes:
  - Follow Schedule
  - Permanent Hold
  - 'Off'
current_temperature: 24.1
temperature: 5
current_humidity: 54
hvac_action: 'off'
preset_mode: 'Off'
friendly_name: Thermo
supported_features: 17
```
